[build]
  functions = "netlify/functions"   # This tells Netlify where your functions live
  publish = "build"                 # This tells Netlify to deploy your React build folder

[functions]
  node_bundler = "esbuild"          # Helps Netlify bundle your functions correctly
